set_override:
  fields:
    device_id:
      required: false
      selector:
        device:
          integration: anode_battery
    hub_id:
      required: false
      example: "ehxbt"
      selector:
        text:
    mode:
      required: true
      example: "CHARGE"
      selector:
        select:
          options:
            - "CHARGE"
            - "DISCHARGE"
            - "IDLE"
            - "MATCH"
    duration:
      required: true
      example: 3600
      selector:
        number:
          min: 0
          max: 604800
          step: 1
          mode: box
          unit_of_measurement: s

cancel_override:
  fields:
    device_id:
      required: false
      selector:
        device:
          integration: anode_battery
    hub_id:
      required: false
      example: "ehxbt"
      selector:
        text:
