"""Client library for the Anode cloud API.

Deliberately free of Home Assistant imports so it can be published to PyPI
as a standalone package and listed in the manifest's ``requirements``.
"""
from .client import API_BASE_URL, LINK_CLIENT_KIND, LINK_SCOPES, AnodeClient
from .exceptions import (
    AnodeAuthError,
    AnodeCommandError,
    AnodeConnectionError,
    AnodeError,
    AnodeForbiddenError,
    AnodeHubOfflineError,
    AnodeHubRefusedError,
    AnodeLinkDeniedError,
    AnodeLinkExpiredError,
    AnodeLinkFailedError,
    AnodeNotFoundError,
    AnodeRateLimitError,
    AnodeResponseError,
    AnodeUpdateInProgressError,
)
from .models import (
    BINDING_HUB,
    SCOPE_DEVICE_CONTROL,
    SCOPE_DEVICE_FIRMWARE,
    SCOPE_DEVICE_READ,
    AccountHub,
    BatteryReading,
    BmsReading,
    DeviceMetadata,
    FirmwareUpdateResult,
    FirmwareUpgrade,
    HubStatus,
    LinkCode,
    LinkGrant,
    MeterReading,
    MeterType,
    OperatingMode,
    PowerLimit,
    PowerLimitKey,
    ProductCode,
    ReleaseNote,
    ScheduleSlot,
    SocLimits,
    SubDevice,
)

__all__ = [
    "API_BASE_URL",
    "BINDING_HUB",
    "LINK_CLIENT_KIND",
    "LINK_SCOPES",
    "SCOPE_DEVICE_CONTROL",
    "SCOPE_DEVICE_FIRMWARE",
    "SCOPE_DEVICE_READ",
    "AccountHub",
    "AnodeAuthError",
    "AnodeClient",
    "AnodeCommandError",
    "AnodeConnectionError",
    "AnodeError",
    "AnodeForbiddenError",
    "AnodeHubOfflineError",
    "AnodeHubRefusedError",
    "AnodeLinkDeniedError",
    "AnodeLinkExpiredError",
    "AnodeLinkFailedError",
    "AnodeNotFoundError",
    "AnodeRateLimitError",
    "AnodeResponseError",
    "AnodeUpdateInProgressError",
    "BatteryReading",
    "BmsReading",
    "DeviceMetadata",
    "FirmwareUpdateResult",
    "FirmwareUpgrade",
    "HubStatus",
    "LinkCode",
    "LinkGrant",
    "MeterReading",
    "MeterType",
    "OperatingMode",
    "PowerLimit",
    "PowerLimitKey",
    "ProductCode",
    "ReleaseNote",
    "ScheduleSlot",
    "SocLimits",
    "SubDevice",
]
